/**
 * RSC-06 — where the chatbot's language model comes from.
 *
 * One integration, any provider. Hugging Face's router, OpenAI, Ollama and most
 * others all speak the same OpenAI-compatible `/chat/completions` shape, so this
 * holds a base URL, a key and a model name rather than an SDK per vendor. No new
 * dependency: native fetch posts JSON.
 *
 * Switching provider is three lines of .env, not a rewrite:
 *
 *   Hugging Face   AI_BASE_URL=https://router.huggingface.co/v1
 *                  AI_API_KEY=hf_...                AI_MODEL=meta-llama/Llama-3.1-8B-Instruct
 *   OpenAI         AI_BASE_URL=https://api.openai.com/v1
 *                  AI_API_KEY=sk-...                AI_MODEL=gpt-4o-mini
 *   Ollama, local  AI_BASE_URL=http://127.0.0.1:11434/v1
 *                  AI_API_KEY=ollama                AI_MODEL=llama3.2
 *
 * COST, because it matters for a student project
 * ----------------------------------------------
 * Hugging Face gives free accounts $0.10 of credits a month and PRO accounts
 * $2.00 (checked 2026-08-21). That is enough to demonstrate, not enough to leave
 * running. OpenAI has no free tier and needs billing set up. Ollama runs on your
 * own machine and costs nothing at all, which is the only option with no bill
 * attached — a small model such as llama3.2 works on CPU, just slowly.
 *
 * Nothing is enabled without AI_API_KEY. With no key the chatbot keeps working
 * exactly as it does today, answering from the system's own LSA data, so a
 * missing or expired key can never leave the demo without a chatbot.
 */

const BASE_URL = (process.env.AI_BASE_URL || '').replace(/\/+$/, '');
const API_KEY = process.env.AI_API_KEY || '';
const MODEL = process.env.AI_MODEL || '';
const TIMEOUT_MS = Number(process.env.AI_TIMEOUT_MS) || 20000;

/** Keeps a bad configuration from spending money on long replies. */
const MAX_TOKENS = Number(process.env.AI_MAX_TOKENS) || 400;

/** Only configured when all three are present — a key without a model is a typo. */
function isConfigured() {
  return Boolean(BASE_URL && API_KEY && MODEL);
}

/** What the admin page shows, with the key never included. */
function describe() {
  if (!isConfigured()) {
    return {
      configured: false,
      provider: 'none',
      model: null,
      note: 'No model configured. The chatbot answers from the system\'s own LSA data.',
    };
  }
  const host = (() => { try { return new URL(BASE_URL).host; } catch { return BASE_URL; } })();
  const provider = /openrouter/i.test(host) ? 'OpenRouter'
    : /huggingface/i.test(host) ? 'Hugging Face'
    : /openai/i.test(host) ? 'OpenAI'
    : /localhost|127\.0\.0\.1/.test(host) ? 'Local model'
    : host;
  return { configured: true, provider, model: MODEL, host, note: `Answers are generated by ${MODEL} via ${provider}.` };
}

module.exports = { BASE_URL, API_KEY, MODEL, TIMEOUT_MS, MAX_TOKENS, isConfigured, describe };
